### PR TITLE
feat: drop IP address

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes
- Introduces a setting to Drop IP address. If enabled, the IP address information is completely discarded after doing the Geo-IP lookup.

Was requested in the past too.

## Checklist

-   [ ] Tests for new code

### CODE REVIEW

**Comment by timgl** [comment]
Thanks!!

**Comment by paolodamico** [comment]
🎊🎊, we just need to deploy it now to PostHog Cloud

**Comment by Twixes** [comment]
Hmm, unfortunately we can't, because this is a stateless plugin – i.e. a single instance of it handles events for all projects: Screen Shot 2022-04-04 at 11 09 44
@yakkomajuri What do you suggest are the right steps here?

**Comment by Twixes** [comment]
Reverted this PR for now (#15) to make the plugin installable until we figure this out.

**Comment by yakkomajuri** [comment]
My suggestion is that users set up https://github.com/witty-works/posthog-property-filter-plugin as the last plugin in the order. I'd definitely like to keep this plugin stateless if possible

**Comment by Twixes** [comment]
That plugin does seem super applicable.

**Comment by paolodamico** [comment]
+1, I do think it's really helpful to have this as an option directly on the plugin, plus highlight it more prominently as a feature. I think it's worth encouraging end user privacy preservation as much as possible.

**Pull request merged**
